"""sync_models_with_db

Revision ID: d987b83c7261
Revises: pacing_practice_001
Create Date: 2026-05-14 13:24:10.997914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd987b83c7261'
down_revision = 'pacing_practice_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_event_created_at'), table_name='analytics_event')
    op.drop_index(op.f('ix_analytics_event_event_type'), table_name='analytics_event')
    op.drop_index(op.f('ix_analytics_event_interview_id'), table_name='analytics_event')
    op.drop_index(op.f('ix_analytics_event_user_id'), table_name='analytics_event')
    op.drop_table('analytics_event')
    op.drop_index(op.f('ix_pacing_practice_session_user_level'), table_name='pacing_practice_session')
    op.alter_column('pronunciation_practice', 'difficulty',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('pronunciation_practice', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('ix_pronunciation_practice_created_at'), table_name='pronunciation_practice')
    op.create_index(op.f('ix_pronunciation_practice_difficulty'), 'pronunciation_practice', ['difficulty'], unique=False)
    op.create_index(op.f('ix_pronunciation_practice_status'), 'pronunciation_practice', ['status'], unique=False)
    op.drop_constraint(op.f('question_supplement_interview_question_id_key'), 'question_supplement', type_='unique')
    op.drop_index(op.f('ix_question_supplement_interview_question_id'), table_name='question_supplement')
    op.create_index(op.f('ix_question_supplement_interview_question_id'), 'question_supplement', ['interview_question_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_supplement_interview_question_id'), table_name='question_supplement')
    op.create_index(op.f('ix_question_supplement_interview_question_id'), 'question_supplement', ['interview_question_id'], unique=False)
    op.create_unique_constraint(op.f('question_supplement_interview_question_id_key'), 'question_supplement', ['interview_question_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_pronunciation_practice_status'), table_name='pronunciation_practice')
    op.drop_index(op.f('ix_pronunciation_practice_difficulty'), table_name='pronunciation_practice')
    op.create_index(op.f('ix_pronunciation_practice_created_at'), 'pronunciation_practice', ['created_at'], unique=False)
    op.alter_column('pronunciation_practice', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('pronunciation_practice', 'difficulty',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_pacing_practice_session_user_level'), 'pacing_practice_session', ['user_id', 'level'], unique=False)
    op.create_table('analytics_event',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], name=op.f('analytics_event_interview_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('analytics_event_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_event_pkey'))
    )
    op.create_index(op.f('ix_analytics_event_user_id'), 'analytics_event', ['user_id'], unique=False)
    op.create_index(op.f('ix_analytics_event_interview_id'), 'analytics_event', ['interview_id'], unique=False)
    op.create_index(op.f('ix_analytics_event_event_type'), 'analytics_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_event_created_at'), 'analytics_event', ['created_at'], unique=False)
    # ### end Alembic commands ###
