"""sync_models_with_db

Revision ID: d987b83c7261
Revises: pacing_practice_001
Create Date: 2026-05-14 13:24:10.997914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd987b83c7261'
down_revision = 'pacing_practice_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_file_name', sa.String(length=256), nullable=False),
    sa.Column('stored_file_name', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_file_created_at'), 'uploaded_file', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_file_created_at'), table_name='uploaded_file')
    op.drop_table('uploaded_file')
    # ### end Alembic commands ###
